const DPSTOPICS = {
    "2_COST_HUNTER_SPELLS": ['bomb toss', 
        'corrosive breath', 
        'cybertech chip', 
        'explosive trap', 
        'flare', 
        'freezing trap', 
        'fresh scent', 
        'goblin prank',
        'hunter\'s mark',
        'misdirection',
        'pressure plate',
        'rat trap',
        'revenge of the wild',
        'snake trap',
        'snipe'
    ],
    "8+_COST_SPELLS": [
        'demonbolt',
        'gift of the wild',
        'lay on hands',
        'power of creation',
        'the forest\'s aid',
        'tip the scales',
        'twisting nether',
        'void contract',
        'mass ressurection',
        'plague of death',
        'the boomship',
        'zerek\'s cloning gallery',
        'dimensional ripper',
        'eye of the storm',
        'puzzle box of yogg-saron',
        'pyroblast'
    ],
    "4_COST_MINIONS_WITH_TAUNT": [
        'annoy-o-module',
        'bone wraith',
        'conjured mirage',
        'dread corsair',
        'felsoul inquisitor',
        'hecklebot',
        'high priestess jeklik',
        'hippogryph',
        'mogu\'shan warden',
        'omega defender',
        'proud defender',
        'sen\'jin shieldmasta',
        'sky gen\'ral kragg',
        'totem cruncher',
        'unpowered steambot',
        'zandalari templar',
        'zul\'drak ritualist'
    ],
    "6_COST_MINIONS_WITH_DEATHRATTLE": [
        'blatant decoy',
        'cairne bloodhoof',
        'coffin crasher',
        'cursed castaway',
        'dr. morrigan',
        'eccentric scribe',
        'khartut defender',
        'mechanical whelp',
        'oblivitron',
        'safeguard',
        'savannah highmane',
        'spark drill',
        'the beast',
        'zerek, master cloner'
    ],
    "EPIC_RARITY_WEAPONS": [
        'doomhammer',
        'gladiator\'s longbow',
        'gorehowl',
        'livewire lance',
        'spectral cutlass',
        'splitting axe',
        'stormhammer',
        'sul\'thraze',
        'supercollider',
        'sword of justice',
        'waggle pick',
        'wrenchcaliber'
    ],
    "0_COST_COMMON_RARITY_CARDS": [
        'beakered lightning',
        'circle of healing',
        'elemental evocation',
        'inner rage',
        'mutate',
        'pounce',
        'regenerate',
        'shadowstep',
        'silence',
        'topsy turvy',
        'totemic surge',
        'whispers of evil',
        'wisp',
        'zap!'
    ],
    "2_COST_BASIC_SET_SPELLS": [
        'arcane explosion',
        'cleave',
        'execute',
        'frostbolt',
        'heroic strike',
        'holy light',
        'hunter\'s mark',
        'mark of the wild',
        'rockbiter weapon',
        'sap',
        'shadow word: death',
        'shadow word: pain',
        'shiv',
        'windfury'
    ],
    "1_COST_CLASSIC_SET_SPELLS": [
        'bestial wrath',
        'blessing of wisdom',
        'call of the void',
        'earth shock',
        'eye for an eye',
        'forked lightning',
        'inner fire',
        'lightning bolt',
        'noble sacrifice',
        'pilfer',
        'redemption',
        'repentance',
        'savagery',
        'shield slam',
        'tome of intellect',
        'upgrade!'
    ],
    "1_COST_DISCOVER_CARDS": [
        'arcane breath',
        'blazing invocation',
        'boom squad',
        'cleric of scales',
        'cloning device',
        'dark possession',
        'dragon\'s hoard',
        'magic trick',
        'omega assembly',
        'secret plan',
        'sinister deal',
        'worthy expedition'
    ],
    "CARDS_WITH_ECHO": [
        'cheap shot',
        'curse of weakness',
        'face collector',
        'ghost light angler',
        'hunting mastiff',
        'phantom militia',
        'pick pocket',
        'sn1p-sn4p',
        'sound the bells!',
        'squashling',
        'walnut sprite',
        'warpath'
    ],
    "4_COST_CARDS_THAT_DRAW_CARDS": [
        'arcane fletcher',
        'arena treasure chest',
        'cult master',
        'forest guide',
        'gnomish inventor',
        'hammer of wrath',
        'juicy psychmelon',
        'mass dispel',
        'murloc tastyfin',
        'predatory instincts',
        'prismatic lens',
        'sandbinder',
        'storm chaser',
        'ticket scalper',
        'veiled worshipper',
        'witchwood piper'
    ],
    "CARDS_WITH_INVOKE": [
        'awaken!',
        'corrupt elementalist',
        'devoted maniac',
        'disciple of galakrond',
        'dragonblight cultist',
        'fiendish rites',
        'invocation of frost',
        'praise galakrond!',
        'ritual chopper',
        'seal fate',
        'shield of galakrond',
        'time rip'
    ],
    "MINIONS_WITH_MAGNETIC": [
        'annoy-o-module',
        'beryllium nullifier',
        'bronze gatekeeper',
        'glow-tron',
        'missile launcher',
        'replicating menace',
        'skaterbot',
        'sn1p-sn4p',
        'spider bomb',
        'venomizer',
        'wargear',
        'zilliax'
    ],
    "1_COST_PALADIN_SPELLS": [
        'autodefense matrix',
        'blessing of might',
        'blessing of wisdom',
        'crystology',
        'desperate measures',
        'eye for an eye',
        'hand of protection',
        'hidden wisdom',
        'humility',
        'never surrender!',
        'noble sacrifice',
        'redemption',
        'repentance',
        'righteous cause',
        'sand breath'
    ],
    "7+_COST_MAGE_CARDS": [
        'animated avalanche',
        'archmage antonidas',
        'astromancer',
        'flamestrike',
        'jan\'alai, the dragonhawk',
        'luna\'s pocket galaxy',
        'hex lord malacrass',
        'mana giant',
        'power of creation',
        'tortollan pilgrim',
        'kalecgos',
        'puzzle box of yogg-saron',
        'pyroblast',
        'the amazing reno'
    ],
    "MAGE_ELEMENTAL_MINIONS": [
        'animated avalanche',
        'arcane amplifier',
        'arcanosaur',
        'bonfire elemental',
        'celestial emissary',
        'chenvaala',
        'cloud prince',
        'cosmic anomaly',
        'mana cyclone',
        'mana giant',
        'violet spellwing',
        'water elemental'
    ],
    "2_ATTACK_WEAPONS": [
        'headhunter\'s hatchet',
        'bloodclaw',
        'mysterious blade',
        'perdition\'s blade',
        'hooked scimitar',
        'spectral cutlass',
        'stormforged axe',
        'doomhammer',
        'woodcutter\'s axe',
        'overlord\'s whip',
        'livewire lance',
        'ancharrr'
    ],
    "5_ATTACK_4_HEALTH_MINIONS": [
        'veiled worshipper',
        'marsh drake',
        'generous mummy',
        'ancient brewmaster',
        'si:7 infiltrator',
        'evasive feywing',
        'frizz kindleroot',
        'booty bay bootyguard',
        'captain greenskin',
        'harrison jones',
        'dalaran crusader',
        'priestess of elune'
    ],
    "CLASS_CARDS_THAT_DEAL_1_DAMAGE_TO_SINGLE_TARGET": [
        'moonfire',
        'wrath',
        'rapid fire',
        'magic dart frog',
        'shiv',
        'perdition\'s blade',
        'earth shock',
        'frost shock',
        'blood witch',
        'mortal coil',
        'inner rage',
        'improve morale',
        'cruel taskmaster',
        'overlord\'s whip'
    ],
    "CARDS_THAT_GIVE_A_MINION_RUSH": [
        'stampeding roar',
        'houndmaster shaw',
        'goblin prank',
        'serrated tooth',
        'captain hooktusk',
        'fel lord betrug',
        'rocket boots',
        'dr. boom, mad genius',
        'the boomship',
        'the boom reaver',
        'magic carpet',
        'charge'
    ],
    "CARDS_WITH_GAIN_3+_ARMOR": [
        'crystallizer',
        'gurubashi offering',
        'half-time scavenger',
        'ice cream peddler',
        'weapons project',
        'evil quartermaster',
        'shield block',
        'molten breath',
        'emberscale drake',
        'armored goon',
        'ice barrier',
        'steel beetle',
        'bite'
    ]
}

module.exports = DPSTOPICS;